export const THRESHOLDS = {
  RISK_HIGH: 70,
  RISK_MODERATE: 50,
  RISK_INSURANCE_MISMATCH: 60,
  INSURANCE_LOW_CONFIDENCE: 0.5,
  INSURANCE_MARGIN_RATIO_PCT: 15,
  TRADE_LANE_DELAY_FREQUENCY: 0.3,
  TRADE_LANE_DELAY_HIGH: 0.5,
  CARRIER_PERFORMANCE_LOW: 50,
  TRANSIT_DAYS_UNUSUALLY_LONG: 60,
} as const;

export const INTEL_THRESHOLDS = {
  CONGESTION_TRIGGER: 50,
  CONGESTION_CRITICAL: 80,
  DISRUPTION_TRIGGER: 40,
  DISRUPTION_CRITICAL: 70,
  WEATHER_TRIGGER: 40,
  WEATHER_CRITICAL: 70,
  SANCTIONS_TRIGGER: 30,
  SANCTIONS_CRITICAL: 60,
  VESSEL_ANOMALY_TRIGGER: 30,
  MARKET_PRESSURE_TRIGGER: 40,
  MARKET_PRESSURE_HIGH: 70,
  COMPOSITE_INTEL_ELEVATED: 35,
  COMPOSITE_INTEL_HIGH: 55,
  COMPOSITE_INTEL_CRITICAL: 75,
  MULTI_SIGNAL_ESCALATION_COUNT: 3,
  PRICING_MARKET_MAGNITUDE_TRIGGER: 3,
  PRICING_CONGESTION_SURCHARGE_TRIGGER: 65,
} as const;

export const EXTERNAL_REASON_CODES = {
  PORT_CONGESTION_HIGH: "PORT_CONGESTION_HIGH",
  PORT_CONGESTION_CRITICAL: "PORT_CONGESTION_CRITICAL",
  LANE_DISRUPTION_ACTIVE: "LANE_DISRUPTION_ACTIVE",
  LANE_DISRUPTION_CRITICAL: "LANE_DISRUPTION_CRITICAL",
  WEATHER_RISK_ELEVATED: "WEATHER_RISK_ELEVATED",
  WEATHER_RISK_CRITICAL: "WEATHER_RISK_CRITICAL",
  SANCTIONS_MATCH_POSSIBLE: "SANCTIONS_MATCH_POSSIBLE",
  SANCTIONS_MATCH_HIGH_CONFIDENCE: "SANCTIONS_MATCH_HIGH_CONFIDENCE",
  MARKET_RATE_PRESSURE: "MARKET_RATE_PRESSURE",
  MARKET_RATE_SURGE: "MARKET_RATE_SURGE",
  VESSEL_ANOMALY_DETECTED: "VESSEL_ANOMALY_DETECTED",
  MULTI_SIGNAL_ESCALATION: "MULTI_SIGNAL_ESCALATION",
} as const;

export type ExternalReasonCode = (typeof EXTERNAL_REASON_CODES)[keyof typeof EXTERNAL_REASON_CODES];

export const EXPIRY_HOURS: Record<string, Record<string, number>> = {
  CRITICAL: { default: 24 },
  HIGH: { default: 72 },
  MEDIUM: { default: 168 },
  LOW: { default: 336 },
};

export function getExpiryHours(urgency: string, _type: string): number {
  return EXPIRY_HOURS[urgency]?.default ?? 168;
}

export function computeExpiresAt(urgency: string, type: string, now?: Date): Date {
  const hours = getExpiryHours(urgency, type);
  const d = new Date(now ?? Date.now());
  d.setTime(d.getTime() + hours * 60 * 60 * 1000);
  return d;
}
