export function wrapHtml(title: string, body: string, docNumber?: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${esc(title)}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Inter', 'Segoe UI', system-ui, -apple-system, sans-serif; font-size: 11px; color: #1a1a2e; background: #fff; line-height: 1.5; }
  .page { max-width: 800px; margin: 0 auto; padding: 40px 48px; }
  .header { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 3px solid #00BFA6; padding-bottom: 16px; margin-bottom: 24px; }
  .header-left h1 { font-size: 20px; font-weight: 700; color: #0D1219; letter-spacing: 0.02em; }
  .header-left .subtitle { font-size: 11px; color: #6b7280; margin-top: 2px; }
  .header-right { text-align: right; }
  .header-right .doc-number { font-size: 13px; font-weight: 600; color: #00BFA6; }
  .header-right .date { font-size: 10px; color: #6b7280; margin-top: 2px; }
  .parties { display: grid; grid-template-columns: 1fr 1fr; gap: 24px; margin-bottom: 24px; }
  .party-box { padding: 12px 16px; background: #f8f9fb; border: 1px solid #e5e7eb; border-radius: 6px; }
  .party-box .label { font-size: 9px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.08em; color: #00BFA6; margin-bottom: 6px; }
  .party-box .name { font-size: 12px; font-weight: 600; color: #1a1a2e; }
  .party-box .detail { font-size: 10px; color: #6b7280; margin-top: 2px; }
  .section { margin-bottom: 20px; }
  .section-title { font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.06em; color: #0D1219; margin-bottom: 8px; padding-bottom: 4px; border-bottom: 1px solid #e5e7eb; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
  th { background: #f0f1f3; font-size: 9px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.06em; color: #6b7280; padding: 8px 10px; text-align: left; border-bottom: 1px solid #e5e7eb; }
  td { padding: 8px 10px; border-bottom: 1px solid #f0f1f3; font-size: 11px; color: #1a1a2e; }
  tr:last-child td { border-bottom: 1px solid #e5e7eb; }
  .text-right { text-align: right; }
  .text-center { text-align: center; }
  .totals { margin-left: auto; width: 260px; }
  .totals tr td { border-bottom: 1px solid #f0f1f3; }
  .totals .grand-total td { font-weight: 700; font-size: 13px; border-top: 2px solid #00BFA6; border-bottom: none; padding-top: 10px; }
  .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 8px 24px; margin-bottom: 16px; }
  .info-item { display: flex; gap: 6px; }
  .info-item .info-label { font-size: 9px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.06em; color: #6b7280; min-width: 100px; }
  .info-item .info-value { font-size: 11px; color: #1a1a2e; font-weight: 500; }
  .footer { margin-top: 32px; padding-top: 12px; border-top: 1px solid #e5e7eb; font-size: 9px; color: #9ca3af; text-align: center; }
  .stamp { display: inline-block; padding: 4px 12px; border: 2px solid #00BFA6; color: #00BFA6; font-weight: 700; font-size: 12px; letter-spacing: 0.1em; transform: rotate(-3deg); margin-top: 16px; }
  .warning { background: #fff3cd; border: 1px solid #ffc107; padding: 8px 12px; border-radius: 4px; font-size: 10px; color: #856404; margin-bottom: 16px; }
  @media print { .page { padding: 20px; } body { font-size: 10px; } }
</style>
</head>
<body>
<div class="page">
${body}
<div class="footer">
  Generated by Dynasties Document Engine &mdash; ${new Date().toISOString().split("T")[0]}
  ${docNumber ? ` &mdash; ${esc(docNumber)}` : ""}
</div>
</div>
</body>
</html>`;
}

export function esc(str: string | null | undefined): string {
  if (!str) return "";
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function formatCurrency(amount: number | string | null | undefined, currency?: string): string {
  const num = typeof amount === "string" ? parseFloat(amount) : amount;
  if (num === null || num === undefined || isNaN(num as number)) return "-";
  const formatted = (num as number).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  return currency ? `${currency} ${formatted}` : formatted;
}

export function formatDate(date: string | Date | null | undefined): string {
  if (!date) return "-";
  const d = new Date(date);
  if (isNaN(d.getTime())) return "-";
  return d.toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
}

export function partyBox(label: string, entity: Record<string, any> | null): string {
  if (!entity) {
    return `<div class="party-box"><div class="label">${esc(label)}</div><div class="name" style="color:#9ca3af">Not assigned</div></div>`;
  }
  return `<div class="party-box">
    <div class="label">${esc(label)}</div>
    <div class="name">${esc(entity.name)}</div>
    ${entity.address ? `<div class="detail">${esc(entity.address)}</div>` : ""}
    ${entity.city || entity.country ? `<div class="detail">${esc([entity.city, entity.country].filter(Boolean).join(", "))}</div>` : ""}
    ${entity.taxId ? `<div class="detail">Tax ID: ${esc(entity.taxId)}</div>` : ""}
    ${entity.contactEmail ? `<div class="detail">${esc(entity.contactEmail)}</div>` : ""}
  </div>`;
}
