import { db } from "./index.js";
import {
  hsCodesTable,
  portsTable,
  containerTypesTable,
  currenciesTable,
  countriesTable,
  incotermsTable,
} from "./schema/index.js";

const HS_CODES = [
  { code: "0301", description: "Live fish", chapter: "03", section: "I" },
  { code: "0901", description: "Coffee, whether or not roasted or decaffeinated", chapter: "09", section: "II" },
  { code: "1001", description: "Wheat and meslin", chapter: "10", section: "II" },
  { code: "2204", description: "Wine of fresh grapes", chapter: "22", section: "IV" },
  { code: "2709", description: "Petroleum oils, crude", chapter: "27", section: "V" },
  { code: "2710", description: "Petroleum oils, not crude", chapter: "27", section: "V" },
  { code: "3004", description: "Medicaments in measured doses", chapter: "30", section: "VI" },
  { code: "3808", description: "Insecticides, herbicides, disinfectants", chapter: "38", section: "VI" },
  { code: "3926", description: "Other articles of plastics", chapter: "39", section: "VII" },
  { code: "4011", description: "New pneumatic tires, of rubber", chapter: "40", section: "VII" },
  { code: "4202", description: "Trunks, suitcases, briefcases, handbags", chapter: "42", section: "VIII" },
  { code: "4407", description: "Wood sawn or chipped lengthwise", chapter: "44", section: "IX" },
  { code: "4802", description: "Uncoated paper and paperboard", chapter: "48", section: "X" },
  { code: "5208", description: "Woven fabrics of cotton", chapter: "52", section: "XI" },
  { code: "6110", description: "Jerseys, pullovers, cardigans, knitted", chapter: "61", section: "XI" },
  { code: "6403", description: "Footwear with rubber/plastic soles, leather uppers", chapter: "64", section: "XII" },
  { code: "6802", description: "Worked monumental or building stone", chapter: "68", section: "XIII" },
  { code: "6911", description: "Tableware and kitchenware, porcelain or china", chapter: "69", section: "XIII" },
  { code: "7010", description: "Carboys, bottles, flasks, jars of glass", chapter: "70", section: "XIII" },
  { code: "7207", description: "Semi-finished products of iron or non-alloy steel", chapter: "72", section: "XV" },
  { code: "7304", description: "Tubes, pipes, of iron or steel, seamless", chapter: "73", section: "XV" },
  { code: "7606", description: "Aluminum plates, sheets, strip", chapter: "76", section: "XV" },
  { code: "8409", description: "Parts for internal combustion engines", chapter: "84", section: "XVI" },
  { code: "8414", description: "Air or vacuum pumps, compressors", chapter: "84", section: "XVI" },
  { code: "8431", description: "Parts for cranes, lifts, excavating machinery", chapter: "84", section: "XVI" },
  { code: "8443", description: "Printing machinery, printers, copiers", chapter: "84", section: "XVI" },
  { code: "8471", description: "Automatic data processing machines (computers)", chapter: "84", section: "XVI" },
  { code: "8473", description: "Parts and accessories for computers", chapter: "84", section: "XVI" },
  { code: "8501", description: "Electric motors and generators", chapter: "85", section: "XVI" },
  { code: "8504", description: "Electrical transformers, converters", chapter: "85", section: "XVI" },
  { code: "8517", description: "Telephone sets, smartphones, communication apparatus", chapter: "85", section: "XVI" },
  { code: "8523", description: "Discs, tapes, solid-state storage devices", chapter: "85", section: "XVI" },
  { code: "8528", description: "Monitors, projectors, television receivers", chapter: "85", section: "XVI" },
  { code: "8534", description: "Printed circuits", chapter: "85", section: "XVI" },
  { code: "8541", description: "Semiconductor devices, LEDs", chapter: "85", section: "XVI" },
  { code: "8542", description: "Electronic integrated circuits", chapter: "85", section: "XVI" },
  { code: "8703", description: "Motor cars and other motor vehicles", chapter: "87", section: "XVII" },
  { code: "8708", description: "Parts and accessories for motor vehicles", chapter: "87", section: "XVII" },
  { code: "8802", description: "Aircraft, spacecraft, and parts", chapter: "88", section: "XVII" },
  { code: "9001", description: "Optical fibers, lenses, prisms", chapter: "90", section: "XVIII" },
  { code: "9013", description: "Liquid crystal devices, lasers, optical instruments", chapter: "90", section: "XVIII" },
  { code: "9018", description: "Medical, surgical, dental instruments", chapter: "90", section: "XVIII" },
  { code: "9021", description: "Orthopedic appliances, artificial body parts", chapter: "90", section: "XVIII" },
  { code: "9401", description: "Seats and parts thereof", chapter: "94", section: "XX" },
  { code: "9403", description: "Other furniture and parts thereof", chapter: "94", section: "XX" },
  { code: "9405", description: "Lamps, light fittings, illuminated signs", chapter: "94", section: "XX" },
  { code: "9503", description: "Tricycles, scooters, toys, puzzles, models", chapter: "95", section: "XX" },
  { code: "9506", description: "Sports equipment, swimming pools, skating", chapter: "95", section: "XX" },
  { code: "9615", description: "Combs, hair-slides, hairpins", chapter: "96", section: "XX" },
  { code: "9701", description: "Paintings, drawings, pastels, original art", chapter: "97", section: "XXI" },
];

const PORTS = [
  { locode: "CNSHA", name: "Shanghai", country: "China", countryCode: "CN", portType: "SEA" as const },
  { locode: "CNSZX", name: "Shenzhen", country: "China", countryCode: "CN", portType: "SEA" as const },
  { locode: "CNNBO", name: "Ningbo", country: "China", countryCode: "CN", portType: "SEA" as const },
  { locode: "CNQIN", name: "Qingdao", country: "China", countryCode: "CN", portType: "SEA" as const },
  { locode: "CNTAO", name: "Tianjin", country: "China", countryCode: "CN", portType: "SEA" as const },
  { locode: "CNXMN", name: "Xiamen", country: "China", countryCode: "CN", portType: "SEA" as const },
  { locode: "HKHKG", name: "Hong Kong", country: "Hong Kong", countryCode: "HK", portType: "SEA" as const },
  { locode: "SGSIN", name: "Singapore", country: "Singapore", countryCode: "SG", portType: "SEA" as const },
  { locode: "KRPUS", name: "Busan", country: "South Korea", countryCode: "KR", portType: "SEA" as const },
  { locode: "JPYOK", name: "Yokohama", country: "Japan", countryCode: "JP", portType: "SEA" as const },
  { locode: "JPTYO", name: "Tokyo", country: "Japan", countryCode: "JP", portType: "SEA" as const },
  { locode: "THLCH", name: "Laem Chabang", country: "Thailand", countryCode: "TH", portType: "SEA" as const },
  { locode: "VNSGN", name: "Ho Chi Minh City", country: "Vietnam", countryCode: "VN", portType: "SEA" as const },
  { locode: "VNHPH", name: "Haiphong", country: "Vietnam", countryCode: "VN", portType: "SEA" as const },
  { locode: "MYPKG", name: "Port Klang", country: "Malaysia", countryCode: "MY", portType: "SEA" as const },
  { locode: "IDTPP", name: "Tanjung Priok (Jakarta)", country: "Indonesia", countryCode: "ID", portType: "SEA" as const },
  { locode: "TWKHH", name: "Kaohsiung", country: "Taiwan", countryCode: "TW", portType: "SEA" as const },
  { locode: "INBOM", name: "Mumbai (Nhava Sheva)", country: "India", countryCode: "IN", portType: "SEA" as const },
  { locode: "INMAA", name: "Chennai", country: "India", countryCode: "IN", portType: "SEA" as const },
  { locode: "INKOL", name: "Kolkata", country: "India", countryCode: "IN", portType: "SEA" as const },
  { locode: "AEJEA", name: "Jebel Ali (Dubai)", country: "United Arab Emirates", countryCode: "AE", portType: "SEA" as const },
  { locode: "SAJED", name: "Jeddah", country: "Saudi Arabia", countryCode: "SA", portType: "SEA" as const },
  { locode: "EGPSD", name: "Port Said", country: "Egypt", countryCode: "EG", portType: "SEA" as const },
  { locode: "DEHAM", name: "Hamburg", country: "Germany", countryCode: "DE", portType: "SEA" as const },
  { locode: "NLRTM", name: "Rotterdam", country: "Netherlands", countryCode: "NL", portType: "SEA" as const },
  { locode: "BEANR", name: "Antwerp", country: "Belgium", countryCode: "BE", portType: "SEA" as const },
  { locode: "ESBCN", name: "Barcelona", country: "Spain", countryCode: "ES", portType: "SEA" as const },
  { locode: "ITGOA", name: "Genoa", country: "Italy", countryCode: "IT", portType: "SEA" as const },
  { locode: "GRPIR", name: "Piraeus", country: "Greece", countryCode: "GR", portType: "SEA" as const },
  { locode: "GBFXT", name: "Felixstowe", country: "United Kingdom", countryCode: "GB", portType: "SEA" as const },
  { locode: "GBLGP", name: "London Gateway", country: "United Kingdom", countryCode: "GB", portType: "SEA" as const },
  { locode: "FRLEH", name: "Le Havre", country: "France", countryCode: "FR", portType: "SEA" as const },
  { locode: "USNYC", name: "New York / Newark", country: "United States", countryCode: "US", portType: "SEA" as const },
  { locode: "USLAX", name: "Los Angeles", country: "United States", countryCode: "US", portType: "SEA" as const },
  { locode: "USLGB", name: "Long Beach", country: "United States", countryCode: "US", portType: "SEA" as const },
  { locode: "USSAV", name: "Savannah", country: "United States", countryCode: "US", portType: "SEA" as const },
  { locode: "USHOU", name: "Houston", country: "United States", countryCode: "US", portType: "SEA" as const },
  { locode: "USCHI", name: "Chicago", country: "United States", countryCode: "US", portType: "INLAND" as const },
  { locode: "CAHAL", name: "Halifax", country: "Canada", countryCode: "CA", portType: "SEA" as const },
  { locode: "CAVAN", name: "Vancouver", country: "Canada", countryCode: "CA", portType: "SEA" as const },
  { locode: "BRSSZ", name: "Santos", country: "Brazil", countryCode: "BR", portType: "SEA" as const },
  { locode: "COBUN", name: "Buenaventura", country: "Colombia", countryCode: "CO", portType: "SEA" as const },
  { locode: "PAMIT", name: "Manzanillo (Panama)", country: "Panama", countryCode: "PA", portType: "SEA" as const },
  { locode: "MXZLO", name: "Manzanillo (Mexico)", country: "Mexico", countryCode: "MX", portType: "SEA" as const },
  { locode: "ZADUR", name: "Durban", country: "South Africa", countryCode: "ZA", portType: "SEA" as const },
  { locode: "MAPTM", name: "Tanger Med", country: "Morocco", countryCode: "MA", portType: "SEA" as const },
  { locode: "AUMEN", name: "Melbourne", country: "Australia", countryCode: "AU", portType: "SEA" as const },
  { locode: "AUSYD", name: "Sydney", country: "Australia", countryCode: "AU", portType: "SEA" as const },
  { locode: "NZAKL", name: "Auckland", country: "New Zealand", countryCode: "NZ", portType: "SEA" as const },
  { locode: "TRIST", name: "Istanbul (Ambarli)", country: "Turkey", countryCode: "TR", portType: "SEA" as const },
];

const CONTAINER_TYPES = [
  { code: "20GP", description: "20ft General Purpose", lengthFt: 20, category: "DRY" as const, maxPayloadKg: 28200, teu: 1 },
  { code: "40GP", description: "40ft General Purpose", lengthFt: 40, category: "DRY" as const, maxPayloadKg: 28800, teu: 2 },
  { code: "40HC", description: "40ft High Cube", lengthFt: 40, category: "DRY" as const, maxPayloadKg: 28560, teu: 2 },
  { code: "20RF", description: "20ft Reefer", lengthFt: 20, category: "REEFER" as const, maxPayloadKg: 27400, teu: 1 },
  { code: "40RF", description: "40ft Reefer", lengthFt: 40, category: "REEFER" as const, maxPayloadKg: 27700, teu: 2 },
  { code: "40RH", description: "40ft Reefer High Cube", lengthFt: 40, category: "REEFER" as const, maxPayloadKg: 29150, teu: 2 },
  { code: "20OT", description: "20ft Open Top", lengthFt: 20, category: "OPEN_TOP" as const, maxPayloadKg: 28100, teu: 1 },
  { code: "40OT", description: "40ft Open Top", lengthFt: 40, category: "OPEN_TOP" as const, maxPayloadKg: 26630, teu: 2 },
  { code: "20FR", description: "20ft Flat Rack", lengthFt: 20, category: "FLAT_RACK" as const, maxPayloadKg: 31200, teu: 1 },
  { code: "40FR", description: "40ft Flat Rack", lengthFt: 40, category: "FLAT_RACK" as const, maxPayloadKg: 40000, teu: 2 },
  { code: "20TK", description: "20ft Tank Container", lengthFt: 20, category: "TANK" as const, maxPayloadKg: 26000, teu: 1 },
  { code: "45HC", description: "45ft High Cube", lengthFt: 45, category: "DRY" as const, maxPayloadKg: 27600, teu: 2 },
];

const CURRENCIES = [
  { code: "USD", name: "US Dollar", symbol: "$" },
  { code: "EUR", name: "Euro", symbol: "€" },
  { code: "GBP", name: "British Pound", symbol: "£" },
  { code: "JPY", name: "Japanese Yen", symbol: "¥" },
  { code: "CNY", name: "Chinese Yuan", symbol: "¥" },
  { code: "KRW", name: "South Korean Won", symbol: "₩" },
  { code: "SGD", name: "Singapore Dollar", symbol: "S$" },
  { code: "HKD", name: "Hong Kong Dollar", symbol: "HK$" },
  { code: "AUD", name: "Australian Dollar", symbol: "A$" },
  { code: "CAD", name: "Canadian Dollar", symbol: "C$" },
  { code: "CHF", name: "Swiss Franc", symbol: "CHF" },
  { code: "INR", name: "Indian Rupee", symbol: "₹" },
  { code: "AED", name: "UAE Dirham", symbol: "د.إ" },
  { code: "BRL", name: "Brazilian Real", symbol: "R$" },
  { code: "MXN", name: "Mexican Peso", symbol: "$" },
  { code: "ZAR", name: "South African Rand", symbol: "R" },
  { code: "THB", name: "Thai Baht", symbol: "฿" },
  { code: "VND", name: "Vietnamese Dong", symbol: "₫" },
  { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp" },
  { code: "MYR", name: "Malaysian Ringgit", symbol: "RM" },
  { code: "SAR", name: "Saudi Riyal", symbol: "﷼" },
  { code: "TRY", name: "Turkish Lira", symbol: "₺" },
  { code: "TWD", name: "Taiwan Dollar", symbol: "NT$" },
  { code: "NZD", name: "New Zealand Dollar", symbol: "NZ$" },
];

const COUNTRIES = [
  { code: "US", name: "United States", region: "Americas", subRegion: "North America" },
  { code: "CN", name: "China", region: "Asia", subRegion: "East Asia" },
  { code: "DE", name: "Germany", region: "Europe", subRegion: "Western Europe" },
  { code: "JP", name: "Japan", region: "Asia", subRegion: "East Asia" },
  { code: "GB", name: "United Kingdom", region: "Europe", subRegion: "Northern Europe" },
  { code: "FR", name: "France", region: "Europe", subRegion: "Western Europe" },
  { code: "IN", name: "India", region: "Asia", subRegion: "South Asia" },
  { code: "KR", name: "South Korea", region: "Asia", subRegion: "East Asia" },
  { code: "IT", name: "Italy", region: "Europe", subRegion: "Southern Europe" },
  { code: "BR", name: "Brazil", region: "Americas", subRegion: "South America" },
  { code: "CA", name: "Canada", region: "Americas", subRegion: "North America" },
  { code: "AU", name: "Australia", region: "Oceania", subRegion: "Oceania" },
  { code: "MX", name: "Mexico", region: "Americas", subRegion: "Central America" },
  { code: "SG", name: "Singapore", region: "Asia", subRegion: "Southeast Asia" },
  { code: "NL", name: "Netherlands", region: "Europe", subRegion: "Western Europe" },
  { code: "BE", name: "Belgium", region: "Europe", subRegion: "Western Europe" },
  { code: "ES", name: "Spain", region: "Europe", subRegion: "Southern Europe" },
  { code: "TH", name: "Thailand", region: "Asia", subRegion: "Southeast Asia" },
  { code: "VN", name: "Vietnam", region: "Asia", subRegion: "Southeast Asia" },
  { code: "MY", name: "Malaysia", region: "Asia", subRegion: "Southeast Asia" },
  { code: "ID", name: "Indonesia", region: "Asia", subRegion: "Southeast Asia" },
  { code: "AE", name: "United Arab Emirates", region: "Asia", subRegion: "Western Asia" },
  { code: "SA", name: "Saudi Arabia", region: "Asia", subRegion: "Western Asia" },
  { code: "TW", name: "Taiwan", region: "Asia", subRegion: "East Asia" },
  { code: "HK", name: "Hong Kong", region: "Asia", subRegion: "East Asia" },
  { code: "ZA", name: "South Africa", region: "Africa", subRegion: "Southern Africa" },
  { code: "EG", name: "Egypt", region: "Africa", subRegion: "North Africa" },
  { code: "MA", name: "Morocco", region: "Africa", subRegion: "North Africa" },
  { code: "TR", name: "Turkey", region: "Europe", subRegion: "Western Asia" },
  { code: "GR", name: "Greece", region: "Europe", subRegion: "Southern Europe" },
  { code: "NZ", name: "New Zealand", region: "Oceania", subRegion: "Oceania" },
  { code: "CO", name: "Colombia", region: "Americas", subRegion: "South America" },
  { code: "PA", name: "Panama", region: "Americas", subRegion: "Central America" },
  { code: "PH", name: "Philippines", region: "Asia", subRegion: "Southeast Asia" },
  { code: "BD", name: "Bangladesh", region: "Asia", subRegion: "South Asia" },
  { code: "PK", name: "Pakistan", region: "Asia", subRegion: "South Asia" },
  { code: "CL", name: "Chile", region: "Americas", subRegion: "South America" },
  { code: "PE", name: "Peru", region: "Americas", subRegion: "South America" },
  { code: "NG", name: "Nigeria", region: "Africa", subRegion: "West Africa" },
  { code: "KE", name: "Kenya", region: "Africa", subRegion: "East Africa" },
];

const INCOTERMS = [
  { code: "EXW", name: "Ex Works", description: "Seller makes goods available at their premises", category: "ANY_MODE" as const },
  { code: "FCA", name: "Free Carrier", description: "Seller delivers goods to carrier at named place", category: "ANY_MODE" as const },
  { code: "CPT", name: "Carriage Paid To", description: "Seller pays carriage to named destination", category: "ANY_MODE" as const },
  { code: "CIP", name: "Carriage and Insurance Paid To", description: "Seller pays carriage and insurance to destination", category: "ANY_MODE" as const },
  { code: "DAP", name: "Delivered at Place", description: "Seller delivers goods at named place of destination", category: "ANY_MODE" as const },
  { code: "DPU", name: "Delivered at Place Unloaded", description: "Seller delivers and unloads at named place", category: "ANY_MODE" as const },
  { code: "DDP", name: "Delivered Duty Paid", description: "Seller delivers goods cleared for import", category: "ANY_MODE" as const },
  { code: "FAS", name: "Free Alongside Ship", description: "Seller delivers alongside vessel at port", category: "SEA_INLAND_WATERWAY" as const },
  { code: "FOB", name: "Free on Board", description: "Seller delivers goods on board the vessel", category: "SEA_INLAND_WATERWAY" as const },
  { code: "CFR", name: "Cost and Freight", description: "Seller pays costs and freight to destination port", category: "SEA_INLAND_WATERWAY" as const },
  { code: "CIF", name: "Cost, Insurance and Freight", description: "Seller pays costs, insurance, and freight", category: "SEA_INLAND_WATERWAY" as const },
];

export async function seedReferenceData() {
  console.log("[seed] Starting reference data seed...");

  await db.insert(hsCodesTable).values(HS_CODES).onConflictDoNothing();
  console.log(`[seed] HS codes: ${HS_CODES.length} records`);

  await db.insert(portsTable).values(PORTS).onConflictDoNothing();
  console.log(`[seed] Ports: ${PORTS.length} records`);

  await db.insert(containerTypesTable).values(CONTAINER_TYPES).onConflictDoNothing();
  console.log(`[seed] Container types: ${CONTAINER_TYPES.length} records`);

  await db.insert(currenciesTable).values(CURRENCIES).onConflictDoNothing();
  console.log(`[seed] Currencies: ${CURRENCIES.length} records`);

  await db.insert(countriesTable).values(COUNTRIES).onConflictDoNothing();
  console.log(`[seed] Countries: ${COUNTRIES.length} records`);

  await db.insert(incotermsTable).values(INCOTERMS).onConflictDoNothing();
  console.log(`[seed] Incoterms: ${INCOTERMS.length} records`);

  console.log("[seed] Reference data seeding complete.");
}
